[tool.black]
line-length = 119
target-version = ["py311"]

[tool.mypy]
python_version = 3.11

[tool.ruff]
select = ["F", "E", "W", "C90", "I", "N", "UP", "RUF"]
fixable = ["ALL"]
line-length = 119
target-version = "py311"
